### ISSUE TITLE
Needs to be slower after adding the TXT record

### ISSUE THREAD

**Issue by landtuna** [josteink/le-godaddy-dns#12]
This failed for me until I added `time.sleep(30)` to end of the `create_txt_record` function.

**Comment by josteink** [comment]
There’s a PR in for that right now, but review is taking some time. 

https://github.com/josteink/le-godaddy-dns/pull/9

**Comment by josteink** [comment]
Fixed in https://github.com/josteink/le-godaddy-dns/pull/9.
