### ISSUE TITLE
godaddy API change needs to be handled.

### ISSUE THREAD

**Issue by gururajahegde** [josteink/le-godaddy-dns#17]
Record takes an array instead of ip

https://github.com/josteink/le-godaddy-dns/blob/487958808ebed568a03ea33949bc86e6b9365680/godaddy.py#L44

Ref: https://developer.godaddy.com/doc/endpoint/domains#/v1/recordReplaceTypeName

**Comment by josteink** [comment]
Right. Would you mind submitting that as a PR?

After all, it's your change, and you deserve the credit :)

**Comment by stevenkaras** [comment]
Isn't this a bug in the upstream[0]?
