### ISSUE TITLE
wildcard certificate

### ISSUE THREAD

**Issue by logicminds** [josteink/le-godaddy-dns#2]
how do I request a wildcard certificate?  ie.  `*.somedomain.com`

**Comment by josteink** [comment]
This is not really a part of the Godaddy DNS challenge-authentication implementation.

This is a issue with ACME as a protocol and Let's Encrypt as a Certificate Authority.

[From their FAQ:](https://community.letsencrypt.org/t/frequently-asked-questions-faq/26)

> Will Let’s Encrypt issue wildcard certificates?
>
> We currently have no plans to do so, but it is a possibility in the future. Hopefully wildcards aren’t necessary for the vast majority of our potential subscribers because it should be easy to get and manage certificates for all subdomains.

As long as let's encrypt doesn't support it, neither can this module.

**Comment by josteink** [comment]
This is not really a part of the Godaddy DNS challenge-authentication implementation.

This is a issue with ACME as a protocol and Let's Encrypt as a Certificate Authority.

[From their FAQ:](https://community.letsencrypt.org/t/frequently-asked-questions-faq/26)

> Will Let’s Encrypt issue wildcard certificates?
>
> We currently have no plans to do so, but it is a possibility in the future. Hopefully wildcards aren’t necessary for the vast majority of our potential subscribers because it should be easy to get and manage certificates for all subdomains.

As long as let's encrypt doesn't support it, neither can this module.

So using wildcards wont work. You either need to enumerate all the domains you need on one line in your `domains.txt-file`, or you need to use another CA.
