### ISSUE TITLE
Possibly insecure dependency - requests

### ISSUE THREAD

**Issue by josteink** [josteink/le-godaddy-dns#24]
Github warns about a possibly insecure dependency: requests.

You can read more here: https://github.com/josteink/le-godaddy-dns/network/alert/requirements.txt/requests/open

Basically Github advices us to upgrade to version 2.20.0.

@JavaScriptDude : Could you test with this version and see if everything still works?

**Comment by JavaScriptDude** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  The link given results to a 404. Can you forward me the full details in an email?                                                                                                                                                                          From: notifications@github.comSent: October 30, 2018 2:09 AMTo: le-godaddy-dns@noreply.github.comReply to: reply@reply.github.comCc: tim.c.quinn@gmail.com; mention@noreply.github.comSubject: [josteink/le-godaddy-dns] Possibly insecure dependency - requests (#24)  Github warns about a possibly insecure dependency: requests.
You can read more here: https://github.com/josteink/le-godaddy-dns/network/alert/requirements.txt/requests/open
Basically Github advices us to upgrade to version 2.20.0.
@JavaScriptDude : Could you test with this version and see if everything still works?

**Comment by JavaScriptDude** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Got it. I read the impacting CVE (CVR-2018-18074). I will pull out my scripts and verify against LE staging tonight. Production testing should not fail differently than Staging so I may not test that. Regarding severity for this project I would rate this as low impact. It appears that the issue only occurs during redirect from http to https on client calls out from request API. As all http calls are to https URLs (LE and godaddy), most people would never hit the usecase that exposes this CVE. However for optics and best practise, I will get this tested ASAP.                                                                                                                                                                           From: notifications@github.comSent: October 30, 2018 2:33 PMTo: le-godaddy-dns@noreply.github.comReply to: reply@reply.github.comCc: tim.c.quinn@gmail.com; mention@noreply.github.comSubject: Re: [josteink/le-godaddy-dns] Possibly insecure dependency - requests (#24)  Sure thing. Here it is:

**Comment by josteink** [comment]
Yeah. Technically speaking I don't think we should be impacted in any real world use-case, but it would be nice to stay on versions without known vulnerabilities as a general rule.

**Comment by JavaScriptDude** [comment]
Tested and verified on both LE staging and production. All is good with switch to request module v2.20.0.

**Comment by josteink** [comment]
Great. Thanks for the help!
