### ISSUE TITLE
remove tld dependency

### ISSUE THREAD

**Issue by JavaScriptDude** [josteink/le-godaddy-dns#25]
I just discovered by accident that tld fundamentally changed their API between current head version and 0.7.9.  The new version of get_tld operates differently and causes an odd error downstream in call using godaddypy.

The issue with depending on an old version of this library is that we are polluting peoples libraries with an old version and if the same person has another library that requires a newer version, it will cause issues.

I suggest that we either align to the current version -or- remove the dependency and implement the code locally.

**Comment by josteink** [comment]
Tlds are a lot more complex than one might immediately assume, so trying to handle those ourselves is just making a trap for future, latent bugs. 

If those are our two options, let’s align with the new API now and avoid bugs in the future.

**Comment by JavaScriptDude** [comment]
I was reading through the tld test cases and yes, I agree. If we upgraded to latest, we just need to use get_fld() instead of get_tld(). 

I'll do this when I get an opening. 

Thanks.

**Comment by JavaScriptDude** [comment]
Fixed with merged pull request #28
