### ISSUE TITLE
Can not renew wildcard. Godaddy API error

### ISSUE THREAD

**Issue by yg85** [josteink/le-godaddy-dns#26]
When I try to renew my certificate I get:
```
+ add -or- update TXT '_acme-challenge.mydomain.com' to 'NlQfIx4jCfps4j2OWqGP7IciV_1_u95IKE1zWYD_RTQ'.
 + Add TXT record for _acme-challenge.mydomain.com | token = 'NlQfIx4jCfps4j2OWqGP7IciV_1_u95IKE1zWYD_RTQ' | zone = 'com' | godaddypy rec = '{'name': '_acme-challenge.mydomain', 'data': 'NlQfIx4jCfps4j2OWqGP7IciV_1_u95IKE1zWYD_RTQ', 'ttl': 600, 'type': 'TXT'}'
Error returned during add: Response Data: {'code': 'INVALID_BODY', 'fields': [{'code': 'MISMATCH_FORMAT', 'message': "does not conform to the 'domain' format, based on pattern: /^[^.]{1,63}(\\.[^.]{1,63})+$/", 'path': 'path.domain'}], 'message': "Request body doesn't fulfill schema, see details in `fields`"}.
```
Any idea where to look?

**Comment by JavaScriptDude** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;} Verify that you have the correct version of tld package installed. Readme.md specifies the right versions.                                                                                                                                                                         Sent via the BlackBerry Hub for Android                                                                                                                                                                           From: notifications@github.comSent: November 21, 2018 9:30 AMTo: le-godaddy-dns@noreply.github.comReply to: reply@reply.github.comCc: subscribed@noreply.github.comSubject: [josteink/le-godaddy-dns] Can not renew wildcard. Godaddy API error (#26)  When I try to renew my certificate I get:
+ add -or- update TXT '_acme-challenge.mydomain.com' to 'NlQfIx4jCfps4j2OWqGP7IciV_1_u95IKE1zWYD_RTQ'.
 + Add TXT record for _acme-challenge.mydomain.com | token = 'NlQfIx4jCfps4j2OWqGP7IciV_1_u95IKE1zWYD_RTQ' | zone = 'com' | godaddypy rec = '{'name': '_acme-challenge.mydomain', 'data': 'NlQfIx4jCfps4j2OWqGP7IciV_1_u95IKE1zWYD_RTQ', 'ttl': 600, 'type': 'TXT'}'
Error returned during add: Response Data: {'code': 'INVALID_BODY', 'fields': [{'code': 'MISMATCH_FORMAT', 'message': "does not conform to the 'domain' format, based on pattern: /^[^.]{1,63}(\\.[^.]{1,63})+$/", 'path': 'path.domain'}], 'message': "Request body doesn't fulfill schema, see details in `fields`"}.

Any idea where to look?

**Comment by josteink** [comment]
The regexp in the error will only fail if

1. Domain-name is very long
2. Domain-name is incomplete. 

What domain are you trying to get/renew cert for?

**Comment by yg85** [comment]
Domain consisted only out of 7 characters.com. It turned out to be WSL problem (not sure why) because when I did the same on Mac it worked.
