### ISSUE TITLE
RequestsDependencyWarning: urllib3 (1.25.7) or chardet (3.0.4) doesn't match a supported version!

### ISSUE THREAD

**Issue by jordankaiser** [josteink/le-godaddy-dns#52]
I'm getting the following warning when running `./dehydrated --challenge dns-01 -k $ROOTDIR/le-godaddy-dns/godaddy.py -c`.

```
RequestsDependencyWarning: urllib3 (1.25.7) or chardet (3.0.4) doesn't match a supported version!
```

My certs are being generated like they should however I would like the get rid of this warning if possible.

I've updated urllib3. Running either `pip show urllib3` or `sudo pip show urllib3` is showing it's version as 1.25.7.

**Comment by josteink** [comment]
From what I can tell, the error reported is that the `requests`-package expects a different version of `urllib3`.

We're currently using requests `2.21.0`. From [what I can tell](https://2.python-requests.org/en/master/community/updates/#id1) upgrading to requests `2.22.0` should solve this.

Could you please test that for me?

**Comment by jordankaiser** [comment]
Your suggestion resolved the warning I was getting. Here is the command I ran to that ended up fixing it.

`sudo -H python3 -m pip install requests==2.22.0`

Thank you for your response and your work on this!
