### ISSUE TITLE
Cut down on supported python versions?

### ISSUE THREAD

**Issue by josteink** [josteink/le-godaddy-dns#58]
Right  now `le-godaddy-dns` [supports Python 3.5 and up](https://github.com/josteink/le-godaddy-dns/blob/master/.travis.yml). I have no deep issue with that, apart from dependencies like `tld` starting to drop support.

That leaves us the choice to either upgrade packages and limit python-support, or keep supporting older python-versions, but being prevented from upgrading dependencies.

Given that:

* [Python 3.4 is EOLed](https://www.python.org/downloads/release/python-340/).
* Debian stable (which from a developer point off view ships stone-age versions of software) is on Python 3.7.
* And dependencies starting to require 3.6 minimum...

I'm inclined to drop support for Python 3.5, in favour of being able to use up-to-date packages.

Anyone have any good reason not to do so? Would it for instance cause issues with RHEL/CentOS deployments?

**Comment by JavaScriptDude** [comment]
I don't see any issues for my usecases. I could see some extra work for users of certain Linux distributions with default Python version that's old. however, there are ways to have multiple Python versions on pretty much any OS so this should not be a show stopper.

**Comment by josteink** [comment]
It seems like the main package causing me to consider this (`tld` ) is re-introducing Python 3.5 support, so [the tld PR](https://github.com/josteink/le-godaddy-dns/pull/57) is actually green now.

I guess the author got lots of feedback asking for support to be reintroduced?

Either way,  for now, I see no reason to cut down on supported versions if we don't need to. Let's re-consider when we have to.
